### ISSUE TITLE
Scrolling App Window

### ISSUE THREAD

**Issue by vihar-s1** [vihar-s1/Desktop-Assistant#7]
## *Interacting with Scrollable Windows*

Assistant should be able to scroll any scrollable window that is opened.

## *Expected Result*

commands like:
- "Scroll <direction>" to scroll in the direction little bit
- "Scroll to <direction>" to scroll to the extreme end
- "start scrolling <direction> / end scrolling" to perform slow continuous scrolling operation

where direction can be left, right, up, and/or down depending on the application window.

**Comment by kruti107** [comment]
Hello,
I would like to solve this issue.

**Comment by vihar-s1** [comment]
Keep me updated with the progress of it is going to take few days to complete and all the best 😄

**Comment by RahatAhmed171** [comment]
Hi is this issue still open? would like to contribute

**Comment by vihar-s1** [comment]
yes the issue is still open...was thinking of returning to this project starting from this issue but you can work on it if you want

**Comment by vihar-s1** [comment]
was cleaning things up...accidentally removed the label...still an hacktoberfest issue

**Comment by vihar-s1** [comment]
If you are interested then I will assign this issue to you

**Comment by RahatAhmed171** [comment]
I have just gone over the codebase. I am interested to contribute to this issue.

**Comment by RahatAhmed171** [comment]
Hi, just to know if I am at the right path, the scrolling option will only apply to the apps which can be opened by the Desktop Assistant? Pls correct me if i am wrong.

**Comment by vihar-s1** [comment]
the list of apps to open by desktop assistant is just a random list of apps that I frequented when I first wrote the code...I am looking into ways to remove the dependency on the hardcoded app location list. so, if possible, can you find an approach along the same path as well??

**Comment by vihar-s1** [comment]
Basically when a request to scroll is made, the app tries to scroll whatever application is open in foreground in the mentioned direction irrespective of whether it is opened by the assistant

**Comment by vihar-s1** [comment]
give @RahatAhmed171 100 points
